### PR TITLE
Basecamp theme fixes + #1924: Dropdown menus options are hidden

### PR DESCRIPTION
**Pull request by oliverds**

### CODE REVIEW

**Comment by neo22s** [comment]
I had to manually merge it.

Maybe issues with thoms changes? https://github.com/open-classifieds/openclassifieds2/commit/555a055e4f7972123286d5f7d2b2b9301c981b10

**Comment by oliverds** [comment]
Sorry forgot to push my conflict fix.

**Comment by neo22s** [comment]
its all good with my commit?

**Comment by oliverds** [comment]
New PR. Recompiled admin styles.css

**Pull request closed without merging**
