### PR TITLE
Changing amount of images by database increment and decrement

### PR DESCRIPTION
**Pull request by aescarcha**
Changing the amount of images on database query to avoid errors on concurrent requests

### CODE REVIEW

**Comment by neo22s** [comment]
thanks! let me review on monday ;)

**Comment by neo22s** [comment]
related to https://github.com/open-classifieds/openclassifieds2/issues/1852

**Comment by neo22s** [comment]
Thanks for the PR.

I am not sure I see the advantage of doing it in a separate query. Maybe I am too tired xD

Do you mind explaining? thanks again and sorry ;)

**Comment by aescarcha** [comment]
I don't know how to do the increment on a Kohana save(), if nothing else is changed, save() could be skipped and just do the query.

**Comment by neo22s** [comment]
Yeah we can skip it.

But the question is why is better to do it this way instead of how was before?

thanks!

**Comment by aescarcha** [comment]
Because if you do two concurent requests to delete an image from an ad, in the old code only one will be deleted, because you are using the value stored in memory, which is the same for both requests. This way, the decrease is done directly on the database, and you don't depend on a value fetched from database 300ms ago

**Comment by neo22s** [comment]
aha! you mean for the API, correct?

**Comment by aescarcha** [comment]
Yes, that happens when deleting by API

**Comment by neo22s** [comment]
But you should not really send concurrent requests to the api point until you get the reply from the server :S same issue will happen with this solution.

I agree is faster but it does not fix it. Its a design issue of how the API makes the call then.

Which app are you using that is facing this issue? something you have built? can we see it? whats the url?

**Comment by aescarcha** [comment]
I'm building a concept, an using your API as backend, I'm afraid it can be displayed right now...

The issue happens when you delete several images from an Ad, and then you click save, changes are applied in that moment, so several deleteImage requests are sent at the same time. The frontend is built on AngularJS.

**Comment by neo22s** [comment]
you will face same issue with this SQL solution.

Please contact me privately. chema@open-classifieds.com

**Comment by neo22s** [comment]
waiting for you to contact .... so I cn help privately.

regards

**Pull request closed without merging**
