### PR TITLE
Update fr_FR translations

### PR DESCRIPTION
**Pull request by EmmanuelSimond**
Question regarding NEWLINE:
we can see `<br />\n`
as well as
`\n`
and even 
`\r\n\r\n`

Which one should we use?
Are they encoded somewhere when composing emails contents?

### CODE REVIEW

**Comment by neo22s** [comment]
<br> its correct.

But when doing this translation you used the one from master as latest, no?

thanks

**Comment by EmmanuelSimond** [comment]
using master branch

**Comment by EmmanuelSimond** [comment]
Hi
Please
Still not sure about NEWLINE
What solution to use?
Since received emails are full of empty lines and empty paragraphs,
it makes for VERY long empty block when read on mobile devices

Which one should we use?
`<br />`
or
`<br />\n`
or
`\n`
or  
`\r\n\r\n`

or what else????

thanks

**Comment by neo22s** [comment]
Sorry wrote it before but got stiped

```<br />``` I think is better

**Comment by emanwebdev** [comment]
Hi
where in the open-source is the handling of those E-Mails so we can check/test/convert all these different newlines, 

Normalize

**Pull request merged**
