### PR TITLE
Huge improvement of fr_FR french translation

### PR DESCRIPTION
**Pull request by emanwebdev**

### CODE REVIEW

**Comment by neo22s** [comment]
Please do 1 pull request for all this changes. This makes the task of reviewing lot more complicated. Specially when they are PR of 1 file.

**Comment by neo22s** [comment]
I will not close them yet but please just one PR so I can merge. thanks

**Comment by emanwebdev** [comment]
Hola Chema

> please just one PR so I can merge

unfortunately for this time i cloned the github.com/open-classifieds/openclassifieds2/ so now i do not have privileges to publish changes . 
Actually , i edited those files ONE by ONE here on github.com through the web editor provided !
it was a quite clumsy and a painful details-centric process :( 

sorry, unfortunately for this time it might well have to be done by hand

thanks for your understanding , translating EVERYTHING in decent french has been a HUGE task

best wishes to OC2 and many congratulations for what OC2 is today, BIG job!!

**atentamente**
Emmanuel

**Comment by emanwebdev** [comment]
Hola,

to ease merge process, this might well be useful to you:

All changes & improvements in a nutshell :
https://github.com/RedActin/openclassifieds2/commit/9fc548b3cf118be4d178154e12dedfc1a65e30aa

Thanks for your precious time

**Pull request merged**
