### PR TITLE
Edit ad: selectize.js and load categories/locations from API + Param $version removed + Fixes Model::get_all return

### PR DESCRIPTION
**Pull request by oliverds**
* Param $version removed #1334
* Edit ad: selectize.js and load categories/locations from API
* Fixes Model::get_all return

     Model::get_all was returning NULL when json cannot be decoded. Ex. when advertisement.fields is empty https://github.com/open-classifieds/openclassifieds2/blob/master/install/samples/install.sql.php#L595

### CODE REVIEW

**Comment by neo22s** [comment]
seems to be working all good! :D we need to test more in deep I guess before release ;)

**Comment by oliverds** [comment]
well I have been testing it a lot before pull-request but I agree further testing will be needed before release, specially with loading custom fields from API done.

**Comment by neo22s** [comment]
ok, I will today ;)

**Comment by neo22s** [comment]
Not sure why in yclas works but not in OC :S 

So when I select a category appears the CF, but when choosing another cat with CF do not appear. I do not see any error in the console.

Maybe is my browser?

**Comment by oliverds** [comment]
> Not sure why in yclas works but not in OC :S
> 
> So when I select a category appears the CF, but when choosing another cat with CF do not appear. I do not see any error in the console.
> 
> Maybe is my browser?

Does it happen on publish new, edit an ad or both? On any theme?

Seems to be working fine to me.

**Comment by neo22s** [comment]
Seems to work good, was something with the cache, we will retest again anyway.

We can implement it also in advanced search, no?

**Pull request merged**
