### PR TITLE
Search within a category and more logic term

### PR DESCRIPTION
**Pull request by Chinese1904**
This basically just allows the user to have a search input field within
a category to search that certain category for ads. It’s really fast
and useful to have handy.
Also, another enhancement is just that I changed Price to Price Range,
because it makes a little more sense

### CODE REVIEW

**Comment by Chinese1904** [comment]
sorry, I am somewhat new to github. It actually was my first pr, not too sure why there was two additional commits

**Comment by neo22s** [comment]
Hello!

Thanks contributing. We always have to have an Issue that relates to any topic before we merge so we can discuss all of us whats the best solution for the problem.

For now no problem let me understand what this does.

The commit that makes the changes is this one correct: https://github.com/Chinese1904/openclassifieds2/commit/a328cf321753fce471734af91a4f09c78b7667fe

So its adding a search box when you are browsing a category?

I think its a good idea but I tihnk what we need to do is load the advanced search probably with the custom fields etc...

**Comment by Chinese1904** [comment]
Hi!

As of right now, you have one search form input in the top right corner which searches through all categories and locations. What I added is just another small search form input which you can see here:
http://imgur.com/i1tnc6F
and it searches the category you are currently in with the location that you have selected.
And yes, I do think adding custom forms to the advanced search is a good idea, definitely!

I am working on adding another small list view form, that basically shows everything in one line and has more of view like the Craigslist one, if that's something you are interested in, I could pr that once I am done.

Chris

**Comment by neo22s** [comment]
Absolutely! but first please create an issue for both cases and we see whats the best solution, for instance for this maybe the best is to load the advanced search, although this looks better.

Also you can always activate the advance search as widget  in the header now that I am thinking....so you will have something really similar to what you just did ;)

**Comment by Chinese1904** [comment]
That sounds like a good idea. And it's true that you have the feature to activate the advanced search as a widget in the header, now the "problem" is that no matter what page you are on, that widget is displayed. From with what I have experienced is that I personally use this exact feature all the time on classifieds sites, because it is the fastest way to filter search results. I just barely bought a puppy off of Craigslist and   because Craigslist does not have a puppy category I used their search within their dog category and I searched for puppies. So from my experience it is something really useful.
Nevertheless, you are right, the option of using the advanced search will deliver the same results

**Comment by neo22s** [comment]
thanks a lot :D

**Pull request closed without merging**
